# Generated by Django 4.0.2 on 2022-02-15 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('date_of_birth', models.DateTimeField()),
            ],
            options={
                'db_table': 'actors',
            },
        ),
        migrations.CreateModel(
            name='Actors_movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.actors')),
            ],
            options={
                'db_table': 'actor_movies',
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('release_date', models.DateTimeField()),
                ('running_time', models.IntegerField()),
                ('actor', models.ManyToManyField(through='movies.Actors_movies', to='movies.Actors')),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.AddField(
            model_name='actors_movies',
            name='movies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies'),
        ),
    ]
